In [191]:
import pandas as pd

Umieścić w folderze "../data/movieLens" pobrane dane ze strony(rozpakowane)

title_movies_merged.csv to ramka danych powstała w wyniku poprzedniego łączenia (to co Gabi robiła) worldwide-box z imdb movies. Polecam zapisany plik.csv w folderze "../data/merged/title_movies_merged.csv"

## MOVIE LENS

Z tej bazy przede wszystkim będziemy potrzebować links.csv (ma id do innych też baz) oraz movies.csv (z tytułami, rokiem i gatunkiem) <br><br>

W innych plikach są ratingi osobnych użytkowników oraz słowa, którymi użytkownicy określali film (ale nie zbiorczo, ale osobno dane każdego użytkownika). Jest też tabela, gdzie określana jest trafność tych określeń ludzi. Można wybrać i przypisać do każdego fimu np 5 najbardziej trafnych określeń

In [192]:
links = pd.read_csv("../data/movieLens/links.csv", dtype={'imdbId': str, 'tmdbId' : str})

In [193]:
movies = pd.read_csv("../data/movieLens/movies.csv")
movies.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [194]:
movies = pd.merge(
    movies,
    links,
    on = 'movieId',
    suffixes=('_movies', '_links')
)

In [195]:
movies.head(10)

,movieId,title,genres,imdbId,tmdbId
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,0114709,862
1,2,Jumanji (1995),Adventure|Children|Fantasy,0113497,8844
2,3,Grumpier Old Men (1995),Comedy|Romance,0113228,15602
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,0114885,31357
4,5,Father of the Bride Part II (1995),Comedy,0113041,11862
5,6,Heat (1995),Action|Crime|Thriller,0113277,949
6,7,Sabrina (1995),Comedy|Romance,0114319,11860
7,8,Tom and Huck (1995),Adventure|Children,0112302,45325
8,9,Sudden Death (1995),Action,0114576,9091
9,10,GoldenEye (1995),Action|Adventure|Thriller,0113189,710

In [196]:
movies['year'] = movies['title'].str.extract(r'\((\d{4})\)')
movies['title'] = movies['title'].str.replace(r'\s\(\d{4}\)', '', regex=True)
movies['year'] = pd.to_numeric(movies['year'], errors='coerce')

In [197]:
movies = movies[['movieId', 'imdbId', 'tmdbId', 'title', 'year', 'genres']]

In [198]:
movies.head(10)

,movieId,imdbId,tmdbId,title,year,genres
0,1,0114709,862,Toy Story,1995.0,Adventure|Animation|Children|Comedy|Fantasy
1,2,0113497,8844,Jumanji,1995.0,Adventure|Children|Fantasy
2,3,0113228,15602,Grumpier Old Men,1995.0,Comedy|Romance
3,4,0114885,31357,Waiting to Exhale,1995.0,Comedy|Drama|Romance
4,5,0113041,11862,Father of the Bride Part II,1995.0,Comedy
5,6,0113277,949,Heat,1995.0,Action|Crime|Thriller
6,7,0114319,11860,Sabrina,1995.0,Comedy|Romance
7,8,0112302,45325,Tom and Huck,1995.0,Adventure|Children
8,9,0114576,9091,Sudden Death,1995.0,Action
9,10,0113189,710,GoldenEye,1995.0,Action|Adventure|Thriller

In [199]:
title_movies_merged = pd.read_csv("../data/merged/title_movies_merged.csv")

In [200]:
merged = pd.merge(
    title_movies_merged,
    movies,
    left_on=['originalTitle', 'startYear'],
    right_on=['title', 'year']
)

In [201]:
print(title_movies_merged.shape)
print(movies.shape)
print(merged.shape)

(16824, 14)
(86537, 6)
(9790, 20)

Po połączeniu pliku movies z movieLens pozostało niecałe 10TYS filmów.<br>
Tutaj jednak mamy już zapewnione id do łączenia zarówno z imdb, jak i z tmdb

In [202]:
merged.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres_x', 'title_x',
       'domestic_million_usd', 'overseas_million_usd', 'world_million_usd',
       'year_x', 'movieId', 'imdbId', 'tmdbId', 'title_y', 'year_y',
       'genres_y'],
      dtype='object')

In [203]:
merged = merged[['tconst', 'imdbId', 'tmdbId', 'movieId', 'primaryTitle',
                 'isAdult', 'year_x', 'domestic_million_usd',
                 'overseas_million_usd', 'world_million_usd', 
                 'runtimeMinutes',  'genres_x', 'genres_y', ]]

In [204]:
merged.sort_values('year_x', ascending= False)

,tconst,imdbId,tmdbId,movieId,primaryTitle,isAdult,year_x,domestic_million_usd,overseas_million_usd,world_million_usd,runtimeMinutes,genres_x,genres_y
9770,tt9603212,9603212,575264,288265,Mission: Impossible - Dead Reckoning Part One,0,2023.0,172.1,155.0,327.1,163,"Action,Adventure,Thriller",Action|Adventure|Thriller
9742,tt9185206,9185206,555285,286569,"Are You There God? It's Me, Margaret.",0,2023.0,20.4,NaN,20.4,106,"Comedy,Drama,Family",Comedy|Drama
9179,tt5090568,5090568,667538,286899,Transformers: Rise of the Beasts,0,2023.0,157.1,NaN,157.1,127,"Action,Adventure,Sci-Fi",Action|Adventure|Sci-Fi
9211,tt5198890,5198890,664341,281900,Eileen,0,2023.0,1.4,NaN,1.4,97,"Drama,Mystery,Romance",Drama|Mystery
5660,tt0439572,0439572,298618,286901,The Flash,0,2023.0,108.1,NaN,108.1,144,"Action,Adventure,Fantasy",Action|Adventure|Sci-Fi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,tt0008329,0008329,400749,167812,Mothers of Men,0,1917.0,NaN,0.0,0.0,60,Drama,Drama
3,tt0006333,0006333,30266,62383,"20,000 Leagues Under the Sea",0,1916.0,8.0,NaN,8.0,105,"Action,Adventure,Sci-Fi",Action|Adventure|Sci-Fi
2,tt0005393,0005393,402388,270428,The Girl of the Golden West,0,1915.0,0.1,NaN,0.1,45,"Drama,Romance,Western",Romance|Western
1,tt0005059,0005059,415021,168578,The Captive,0,1915.0,0.1,NaN,0.1,50,"Drama,Romance,War",(no genres listed)
0,tt0003471,0003471,96128,135706,Traffic in Souls,0,1913.0,1.0,NaN,1.0,88,"Crime,Drama",Drama

Próbuję jeszcze połączyć z najważniejszymi słowami kluczowymi

In [205]:
genome_scores = pd.read_csv("../data/movieLens/genome-scores.csv")
genome_tags = pd.read_csv('../data/movieLens/genome-tags.csv')

In [206]:
scores_with_names = pd.merge(genome_scores, genome_tags, on='tagId')
scores_with_names = scores_with_names.sort_values(by=['movieId', 'relevance'], ascending=[True, False])
top5_tags_long = scores_with_names.groupby('movieId').head(5)
top5_tags_final = top5_tags_long.groupby('movieId')['tag'].apply(lambda x: ', '.join(x)).reset_index()
top5_tags_final.rename(columns={'tag': 'top_5_tags'}, inplace=True)

In [207]:
top5_tags_final.head(10)

   movieId                                         top_5_tags
0        1  toys, computer animation, pixar animation, ani...
1        2      adventure, children, fantasy, kids, childhood
2        3     good sequel, sequel, sequels, comedy, original
3        4  women, chick flick, girlie movie, romantic, di...
4        5  good sequel, sequel, sequels, midlife crisis, ...
5        6   crime, heist, imdb top 250, great acting, action
6        7  remake, romantic, romance, romantic comedy, go...
7        8  runaway, adapted from:book, based on a book, n...
8        9  action, good action, lone hero, hostage, actio...
9       10         007 (series), 007, bond, action, franchise

In [208]:
worldWide_imdb_movieLens_merged = pd.merge(
    merged,
    top5_tags_final,
    on = 'movieId',
    how = "left"
)

In [209]:
worldWide_imdb_movieLens_merged.head(10)

,tconst,imdbId,tmdbId,movieId,primaryTitle,isAdult,year_x,domestic_million_usd,overseas_million_usd,world_million_usd,runtimeMinutes,genres_x,genres_y,top_5_tags
0,tt0003471,0003471,96128,135706,Traffic in Souls,0,1913.0,1.0,NaN,1.0,88,"Crime,Drama",Drama,NaN
1,tt0005059,0005059,415021,168578,The Captive,0,1915.0,0.1,NaN,0.1,50,"Drama,Romance,War",(no genres listed),NaN
2,tt0005393,0005393,402388,270428,The Girl of the Golden West,0,1915.0,0.1,NaN,0.1,45,"Drama,Romance,Western",Romance|Western,NaN
3,tt0006333,0006333,30266,62383,"20,000 Leagues Under the Sea",0,1916.0,8.0,NaN,8.0,105,"Action,Adventure,Sci-Fi",Action|Adventure|Sci-Fi,"based on a book, original, silent, science fic..."
4,tt0008329,0008329,400749,167812,Mothers of Men,0,1917.0,NaN,0.0,0.0,60,Drama,Drama,NaN
5,tt0008519,0008519,174708,261661,A Romance of the Redwoods,0,1917.0,0.4,NaN,0.4,70,"Adventure,Comedy,Drama",Drama|Romance,NaN
6,tt0009369,0009369,54242,150964,Mickey,0,1918.0,8.0,NaN,8.0,93,"Comedy,Drama",Comedy|Drama,NaN
7,tt0009440,0009440,174925,157623,Old Wives for New,0,1918.0,0.3,NaN,0.3,60,"Comedy,Crime,Drama",Comedy|Drama|Romance,NaN
8,tt0012067,0012067,308372,228263,A Connecticut Yankee in King Arthur's Court,0,1921.0,0.1,NaN,0.1,80,"Adventure,Comedy,Fantasy",Comedy,NaN
9,tt0012397,0012397,175330,142709,Little Lord Fauntleroy,0,1921.0,0.9,0.2,1.1,112,Drama,Drama,NaN

In [210]:
worldWide_imdb_movieLens_merged.shape

(9790, 14)

In [211]:
worldWide_imdb_movieLens_merged.to_csv("../data/merged/worldWide_imdb_movieLens_merged.csv", index=False)

# TMDB (API)

Pobrałam te dane z tmdb, które łączą się po tmdbId z filmami z ramki worldWide_imdb_movieLens_merged.csv

In [212]:
tmdb = pd.read_csv("../data/tmdb/final_tmdb_data.csv")

In [213]:
print(tmdb.shape)
print(worldWide_imdb_movieLens_merged.shape)

(9660, 17)
(9790, 14)